fix gitea selectors for v1.18
toggl/track-extension pull request #2210
Opened 2023-06-02 15:00 UTC by duncanawoods

## :star2: What does this PR do?

This PR fixes the Gitea extension for new versions for Gitea which have reformatted the issue page.

When debugging the original code, there are two problems:

- the issue id appears after the title not before it as the code expects
- HTMLCollection of tags does not support forEach

These changes have been made.

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

These are fixes for Gitea v1.18. I will test against the latest version v1.19 once we update.

## :memo: Links to relevant issues or information

#2209

2023-06-05 10:08 UTC, duncanawoods commented
Confirmed that it works for latest version of gitea v19.

Only issue is that given a list of tags, they do not appear in the toggle "start task" dialogue. I can confirm in a debugger that the selector produces an array of strings.

2023-06-09 19:16 UTC, Alissonsz requested changes
Hey! Thanks for your contribution.

I noticed that the description is getting a lot of blank spaces, could you fix that? Just a `trim()` should solve it.
![image](https://github.com/toggl/track-extension/assets/38736666/5fa86ac9-8a6f-4f6f-b488-70e83829b0ad)

2023-06-12 07:51 UTC, duncanawoods commented
Hi @Alissonsz thank you for the feedback. I couldn't replicate the excess whitespace but I have trimmed the parsed text anyway. Seems like a decent change to make. What OS/browser were you using?

2023-06-12 17:04 UTC, Alissonsz approved these changes
That's working fine now!! 
Thank you @duncanawoods, I'm testing it on Mac/Chrome.

2023-06-19 14:58 UTC, merged